# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2145eeaa1a0f06f9c0a7746dbdd0d1f81ef568a18f3ca30f48643c9c826c5df97e8cf2b4238ecd6c33c6f7f5f8a0701bb31ed2e4b45ca7e54bc06ecc54ce019

test:
  secret_key_base: f3a6853a4ead38d6a414e1ff02fca664add3098edf77171842ac251c70c19cc644930104541515fb2dc6f9f9ff70402045617a92219ef6d5f689bf0a411a1689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
